### ISSUE TITLE
current examples are not working

### ISSUE THREAD

**Issue by rahulkumar-aws** [alex-oleshkevich/vue-introjs#10]
Current examples are not working and integration instruction in README.md file is also not clear. Please add some nice integration document.

**Comment by cmrd-senya** [comment]
Confirm, I tried this with Rails + Webpack + Vue.js and it didn't work. I ended up using Intro.js directly.

**Comment by alex-oleshkevich** [comment]
@cmrd-senya @rahulkumar-aws what is an exact issue with it?

**Comment by cmrd-senya** [comment]
Here is how I used it in a Vue component:

```
import Vue from 'vue'
import VueIntro from 'vue-intro.js'

Vue.use(VueIntro);
```

This code ran with no errors.

Then I tried to access `Vue.$intro` or `this.$intro` but it failed. Also Vue.js reported me that v-intro-hint directive wasn't registered.

**Comment by alex-oleshkevich** [comment]
ok, i will look into it soon

**Comment by cmrd-senya** [comment]
I will try to provide you with a test application where it fails.

**Comment by genzoadam** [comment]
owww.. this is not work. I urgently need this.

**Comment by alex-oleshkevich** [comment]
I found the issue. It's only reproduced if you use ES5 version. Switch to ES6 to avoid it. I am looking into fix.

**Comment by alex-oleshkevich** [comment]
issue has been fixed.
but prefet ES6 mode since now:

```javascript
import VueIntro from 'vue-introjs';
Vue.use(VueIntro);
```
