### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by maotong06** [alex-oleshkevich/vue-introjs#11]
ERROR in static/js/vendor.d59fade80353c4f96b45.js from UglifyJs
Unexpected token: punc (() [./node_modules/_vue-introjs@1.1.1@vue-introjs/src/index.js:10,0][static/js/vendor.d59fade80353c4f96b45.js:2710,11]

  Build failed with errors.

and 
npm run dev is good

**Comment by alex-oleshkevich** [comment]
load transpiled `vue-intojs/dist/index.min.js`. 

when you do `import 'vue-introjs'` it loads ES6 version of this plugin. UglifyJs does not support it yet out of the box and fails with error. In dev mode you don't run UglifyJs so there is no such error.
