### ISSUE TITLE
UglifyJS issues

### ISSUE THREAD

**Issue by robsonsobral** [alex-oleshkevich/vue-introjs#14]
Hi!

I got stuck into issues when trying to minify VueIntroJs. My solution was to point to the dist file, instead of the `package.json` [`main` value](https://docs.npmjs.com/files/package.json#main), `"src/index.js"`:

```
	resolve: {
		alias: {
			'vue-introjs': 'vue-introjs/dist/index.min.js',
```

Thank you!

**Comment by alex-oleshkevich** [comment]
UglifyJS does not work with ES6 syntax. Your workarond is generally ok

**Comment by robsonsobral** [comment]
Thank you, @alex-oleshkevich . Please, consider to add this info to the readme.

Thank you! Have a nice day!
