### ISSUE TITLE
webpack issues

### ISSUE THREAD

**Issue by ghenry** [alex-oleshkevich/vue-introjs#15]
```
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 95% emitting                                                                           

 WARNING  Compiled with 1 warnings                                                                                                                                                3:26:06 PM

 warning  in ./node_modules/intro.js/introjs.css

(Emitted value instead of an instance of Error) autoprefixer: /home/ghenry/src/SureVoIP-Portal/root/src/client_side/node_modules/intro.js/introjs.css:12:3: Gradient has outdated direction syntax. Replace `cover` to `farthest-corner`.

 @ ./node_modules/intro.js/introjs.css 4:14-114 13:3-17:5 14:22-122
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main.js

```

**Comment by alex-oleshkevich** [comment]
`./node_modules/intro.js/introjs.css` is not a part of this plugin.
i've removed it from package.json

refer the docs for more information

**Comment by ghenry** [comment]
Hi Alex,

Which part of the docs would that be? This set up is like no other vue-*
thing I've used, so please bear with me.

Gavin.

**Comment by ghenry** [comment]
It's trigger by:

// attach CSS
// SomeComponent.vue
import 'intro.js/introjs.css';

**Comment by ghenry** [comment]
I'm using vue-cli with webpack template.

**Comment by ghenry** [comment]
Should I raise the css issue with the introjs team?

I do not want to include the js or css in a html file, but use webpack.

Thanks!

**Comment by alex-oleshkevich** [comment]
Seems that issue us with introjs itself. I will remove that import anyway.

**Comment by ghenry** [comment]
Looks like it's fixed here https://github.com/usablica/intro.js/pull/804
