### ISSUE TITLE
Feature request: Make it possible to set options for an autostarted tour via a directive or directive parameter

### ISSUE THREAD

**Issue by gabriel4649** [alex-oleshkevich/vue-introjs#2]
As I understand, if an tour is started using the autostarted option, there is no way to configure it. It would be great to be able to configure it via a directive or directive paramter. Ideally, the directive or directive parameter would take an object with options.

**Comment by alex-oleshkevich** [comment]
what exactly you want to configure?

**Comment by gabriel4649** [comment]
I want to set the `doneLabel` and set `introJs.oncomplete(providedCallback)`to a callback that programatically changes the page using vue-rouoter. Basically I am doing a multi-page intro.

**Comment by alex-oleshkevich** [comment]
implemeted
