### ISSUE TITLE
vue unit tests

### ISSUE THREAD

**Issue by ghenry** [alex-oleshkevich/vue-introjs#22]
Hi,
I'm having real trouble with IntoJs and testing. Can you have a look at:

https://forums.manning.com/posts/list/0/43203.page#p121739
https://github.com/vuejs/vue-test-utils/issues/570

It seems somewhat related to #19 

Thanks.

**Comment by alex-oleshkevich** [comment]
@ghenry, please, look at #19

**Comment by alex-oleshkevich** [comment]
duplicates #19
