### ISSUE TITLE
Deprecated: please use require("intro.js") directly, instead of the introJs method of the function

### ISSUE THREAD

**Issue by phongpt156** [alex-oleshkevich/vue-introjs#26]
I'm using intro.js version 2.9.3. I got this error when call this.$intro().start(). But version 2.8 work well.

**Comment by sharpFD** [comment]
as well as me

**Comment by Situma** [comment]
I also have the same issue. @zedsimple @wuyungen1996 did you manage to get a solution?

**Comment by alex-oleshkevich** [comment]
@zedsimple @Situma @wuyungen1996 what kind of issue do you have? can you post a trace?
There are no errors when I use example pages (included with this repo).

usablica/intro.js#874

**Comment by alex-oleshkevich** [comment]
https://github.com/usablica/intro.js/issues/874

**Comment by JohnRSim** [comment]
@alex-oleshkevich examples are using v2.7 or intro.js - the issue can be replicated on introjs > 2.8
Also things like setting config options-
```Javascript
this.$intro(config).start(); 
```
No longer work.

The following works - 
```
			self.$intro().setOptions({
				helperElementPadding: 0,
				showStepNumbers: false,
				tooltipClass: 'jseaTooltipInfo',
				highlightClass: 'jseaTooltipHelper',
				disableInteraction: true,
			}).start();
```
