### ISSUE TITLE
This dependency was not found

### ISSUE THREAD

**Issue by vrubliuk** [alex-oleshkevich/vue-introjs#30]
Suddenly, I started to get this error on starting my project. Earlier (few days ago) everything was fine.
--------
This dependency was not found:
* vue-introjs in ./src/main.js
To install it, you can run: npm install --save vue-introjs
--------
My current version of the package is: "vue-introjs": "^1.1.2"
Even if I execute npm install --save vue-introjs and update the package to version 1.3.1, it doesn't help.

**Comment by alex-oleshkevich** [comment]
@vrubliuk, resolved in `1.3.2`.

**Comment by vrubliuk** [comment]
Thank you very much!
