### ISSUE TITLE
Error in mounted hook: "ReferenceError: introJs is not defined"

### ISSUE THREAD

**Issue by jetlej** [alex-oleshkevich/vue-introjs#34]
I'm using electron-vue, which uses vue-cli + webpack. 

I've added this in src/main.js: 

```
import VueIntro from 'vue-introjs'
Vue.use(VueIntro)
```

then added the plugin in `webpack.renderer.config.js` and `webpack.main.config.js: 

```
plugins: [
     [...]
     new webpack.ProvidePlugin({
        introJs: ['intro.js', 'introJs']
    })
],
```

Then when I use the intro directives in a component, I get the error: `Error in mounted hook: "ReferenceError: introJs is not defined"`

Both intro.js and vue-introjs have been installed via NPM

Any ideas?

**Comment by alex-oleshkevich** [comment]
Did you install intro.js?

**Comment by jetlej** [comment]
@alex-oleshkevich  - Yes, both packages were installed via NPM

**Comment by kristoff2016** [comment]
Hey, did you fixed it ? thank you

**Comment by kristoff2016** [comment]
It's worked but I seen in console  `ReferenceError: introJs is not defined `
any ideas ? thank you

**Comment by slavarazum** [comment]
Have the same issue when call `this.$intro().start()`, did anyone resolve it?

**Comment by lspohn** [comment]
Same problem here. Didn't find a solution. Followed the installation guide 1:1 and experienced the same problem. Solution highly appreciated.
I'd suggest to include intro.js in this library as it seems that many struggle with Webpack configs.

**Comment by magdenkov** [comment]
Same problem

**Comment by yunlonglee** [comment]
I using nuxt , that is how make it work

`npm i vue-introjs intro.js --save`

plugins/vue-introjs.ts
```
import Vue from 'vue'
import VueIntro from 'vue-introjs'
import 'intro.js/introjs.css'

Vue.use(VueIntro)
```

nuxt.config.ts
```
const webpack = require('webpack')

plugins: [
  { src: "~/plugins/vue-introjs", ssr: false }
]

build: {
    plugins: [
      new webpack.ProvidePlugin({
        'introJs': ['intro.js']
      })
    ]
  }
```

**Comment by oshell** [comment]
I had to put this into my `vue.config.js` because I am using `vue-cli` and `electron` .

```
const webpack = require('webpack');

module.exports = {
  configureWebpack: {
    plugins: [
      new webpack.ProvidePlugin({
        'introJs': ['intro.js']
      })
    ]
  },
}
```
