### ISSUE TITLE
options hideNext not work

### ISSUE THREAD

**Issue by lwl0812** [alex-oleshkevich/vue-introjs#41]
this.intro = this.$intro();
      this.intro.setOptions({
        hideNext: true, // <-- not work, still shows the next button
        hidePrev: true,
        prevLabel: '上一步',
        nextLabel: '下一步',
        doneLabel: '完成',
        showProgress: true,
        showBullets: false,
        exitOnOverlayClick: false,
        // showButtons: false,
        steps: [
          {
            intro: '点击按钮',
            element: document.querySelector('.list-step0'),
          },
          {}
        ],
      });
      this.intro.start();

options is like above, but the next button is still visible.

**Comment by cookie918** [comment]
我也发现这个问题，现在还不知道怎样解决？我实验的结果：v-intro-autostart = true 时候，config才起作用
